/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sorveteria.view;

import Sorveteria.data.Conexao;
import java.net.URL;
import java.nio.file.Path;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;




/**
 *
 * @author kayo_
 */
public class JFPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFPrincipal
     */
    public JFPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpPrincipal = new javax.swing.JDesktopPane();
        jmPrincipal = new javax.swing.JMenuBar();
        jmCadastro = new javax.swing.JMenu();
        jmiCliente = new javax.swing.JMenuItem();
        jmiFornecedor = new javax.swing.JMenuItem();
        jmiProduto = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmiSair = new javax.swing.JMenuItem();
        jmMovimentacao = new javax.swing.JMenu();
        jmiRealizarVenda = new javax.swing.JMenuItem();
        jmRelatorio = new javax.swing.JMenu();
        jmiClientesCadastrados = new javax.swing.JMenuItem();
        jmiVendas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jdpPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        jdpPrincipal.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jdpPrincipalLayout = new javax.swing.GroupLayout(jdpPrincipal);
        jdpPrincipal.setLayout(jdpPrincipalLayout);
        jdpPrincipalLayout.setHorizontalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 644, Short.MAX_VALUE)
        );
        jdpPrincipalLayout.setVerticalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 392, Short.MAX_VALUE)
        );

        jmPrincipal.setBackground(new java.awt.Color(51, 92, 214));

        jmCadastro.setBackground(new java.awt.Color(51, 92, 214));
        jmCadastro.setText("Cadastro");

        jmiCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jmiCliente.setText("Cliente");
        jmiCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiClienteActionPerformed(evt);
            }
        });
        jmCadastro.add(jmiCliente);

        jmiFornecedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jmiFornecedor.setText("Fornecedor");
        jmiFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFornecedorActionPerformed(evt);
            }
        });
        jmCadastro.add(jmiFornecedor);

        jmiProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jmiProduto.setText("Produto");
        jmiProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiProdutoActionPerformed(evt);
            }
        });
        jmCadastro.add(jmiProduto);
        jmCadastro.add(jSeparator1);

        jmiSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jmiSair.setText("Sair");
        jmCadastro.add(jmiSair);

        jmPrincipal.add(jmCadastro);

        jmMovimentacao.setBackground(new java.awt.Color(51, 92, 214));
        jmMovimentacao.setText("Movimentação");

        jmiRealizarVenda.setText("Realizar Venda");
        jmiRealizarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRealizarVendaActionPerformed(evt);
            }
        });
        jmMovimentacao.add(jmiRealizarVenda);

        jmPrincipal.add(jmMovimentacao);

        jmRelatorio.setText("Relatório");

        jmiClientesCadastrados.setText("Clientes Cadastrados");
        jmiClientesCadastrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiClientesCadastradosActionPerformed(evt);
            }
        });
        jmRelatorio.add(jmiClientesCadastrados);

        jmiVendas.setText("Vendas Realizadas");
        jmiVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiVendasActionPerformed(evt);
            }
        });
        jmRelatorio.add(jmiVendas);

        jmPrincipal.add(jmRelatorio);

        setJMenuBar(jmPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jdpPrincipal)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jdpPrincipal)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiClienteActionPerformed
        JIFCliente janela = new JIFCliente();
        jdpPrincipal.add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_jmiClienteActionPerformed

    private void jmiFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFornecedorActionPerformed
        JIFFornecedor janela = new JIFFornecedor();
        jdpPrincipal.add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_jmiFornecedorActionPerformed

    private void jmiProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiProdutoActionPerformed
        JIFProduto janela = new JIFProduto();
        jdpPrincipal.add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_jmiProdutoActionPerformed

    private void jmiRealizarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRealizarVendaActionPerformed
        JIFVenda janela = new JIFVenda();
        jdpPrincipal.add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_jmiRealizarVendaActionPerformed

    private void jmiClientesCadastradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiClientesCadastradosActionPerformed

        
        int confirma = JOptionPane.showConfirmDialog(this, "Confirma a impressão do relatório de Cadastro de Clientes??","Atenção",JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION) {
            
            URL url = this.getClass().getResource("./../relatorio/RelatorioClientesCadastrados.jasper");
            
            JasperPrint jasperPrint = null;
            
            try {
                //A URL do recurso precisa ser convertida para path de arquivo.
                String path = Path.of(url.toURI()).toString();
                System.out.println("Path para o JRXML: "+path);
            
                
                
                Conexao c = new Conexao();
                jasperPrint = JasperFillManager.fillReport(path, null, c.getConexao());
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Erro ao gerar o Relatório! "+ex.getMessage());
            }
            
            
            
            JasperViewer view = new  JasperViewer(jasperPrint, false);
            view.setVisible(true);
            
        }
        
        
    }//GEN-LAST:event_jmiClientesCadastradosActionPerformed

    private void jmiVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiVendasActionPerformed
        JIFDataVenda janela = new JIFDataVenda();
        jdpPrincipal.add(janela);
        janela.setVisible(true);
        
    }//GEN-LAST:event_jmiVendasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JDesktopPane jdpPrincipal;
    private javax.swing.JMenu jmCadastro;
    private javax.swing.JMenu jmMovimentacao;
    private javax.swing.JMenuBar jmPrincipal;
    private javax.swing.JMenu jmRelatorio;
    private javax.swing.JMenuItem jmiCliente;
    private javax.swing.JMenuItem jmiClientesCadastrados;
    private javax.swing.JMenuItem jmiFornecedor;
    private javax.swing.JMenuItem jmiProduto;
    private javax.swing.JMenuItem jmiRealizarVenda;
    private javax.swing.JMenuItem jmiSair;
    private javax.swing.JMenuItem jmiVendas;
    // End of variables declaration//GEN-END:variables
}
