/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sorveteria.view;

import Sorveteria.data.Conexao;
import java.net.URL;
import java.nio.file.Path;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author kayo_
 */
public class JIFDataVenda extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFDataVenda
     */
    public JIFDataVenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jftDataInicial = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jftDataFinal = new javax.swing.JFormattedTextField();
        jbGerarRelatorio = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("Insira o Período de Vendas:");

        try {
            jftDataInicial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftDataInicial.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel3.setText("até");

        try {
            jftDataFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftDataFinal.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jbGerarRelatorio.setText("Gerar Relatório");
        jbGerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGerarRelatorioActionPerformed(evt);
            }
        });

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel2.setText("(inicial)");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jLabel4.setText("(final)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(123, 123, 123))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jftDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel3)
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbGerarRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel4)))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jftDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jftDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbGerarRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbGerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGerarRelatorioActionPerformed
        try {
            if(validarDados()){
                int confirma = JOptionPane.showConfirmDialog(this, "Confirma a impressão do relatório de Vendas??","Atenção",JOptionPane.YES_NO_OPTION);
                
                if (confirma == JOptionPane.YES_OPTION) {

                    URL url = this.getClass().getResource("./../relatorio/Vendas.jasper");

                    JasperPrint jasperPrint = null;

                    //criar uma lista com as datas para enviar por parametro depois
                    HashMap<String, Object> lista = new HashMap<String, Object>();

                    //formato da data
                    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

                    //criando as variaveis dtInicial e dtFinal do tipo java.sql.Date que é o tipo selecionado no Jasper
                    java.sql.Date dtInicial = new java.sql.Date(sdf.parse(jftDataInicial.getText()).getTime());
                    java.sql.Date dtFinal = new java.sql.Date(sdf.parse(jftDataFinal.getText()).getTime());

                    lista.put("DataInicial",dtInicial);
                    lista.put("DataFinal",dtFinal);

                    //JOptionPane.showMessageDialog(this,"dtIni: "+dtInicial+".... dtFim:"+dtFinal);

                    //A URL do recurso precisa ser convertida para path de arquivo.
                    String path = Path.of(url.toURI()).toString();
                    System.out.println("Path para o JRXML: "+path);

                    Conexao c = new Conexao();
                    jasperPrint = JasperFillManager.fillReport(path, lista, c.getConexao());
                    
                    JasperViewer view = new  JasperViewer(jasperPrint, false);
                    view.setVisible(true);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao gerar relatório: " + e.getMessage(), "Gerar-Relatorio-Vendas", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jbGerarRelatorioActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        Sorveteria.data.extras.Formulario.limparCampos(this);
    }//GEN-LAST:event_jbCancelarActionPerformed
    
    private boolean validarDados() throws Exception{
        if (jftDataInicial.getText().equals("  /  /    ") || jftDataFinal.getText().equals("  /  /    ")) 
            throw new Exception ("Data não informada");

        //usando substring para pegar partes da string como dia, mes e ano
        int diaInicial = Integer.parseInt(jftDataInicial.getText().substring(0,2));
        int mesInicial = Integer.parseInt(jftDataInicial.getText().substring(3,5));
        int anoInicial = Integer.parseInt(jftDataInicial.getText().substring(6,10));
        
        int diaFinal = Integer.parseInt(jftDataFinal.getText().substring(0,2));
        int mesFinal = Integer.parseInt(jftDataFinal.getText().substring(3,5));
        int anoFinal = Integer.parseInt(jftDataFinal.getText().substring(6,10));
        
        Calendar cal = Calendar.getInstance(); //instanciando um objeto calendario
        int year = cal.get(Calendar.YEAR);//obtendo o ano atual
        
        
        if (diaInicial < 1 || diaInicial > 31) 
            throw new Exception ("Dia Inicial informado inválido");
        
        if (mesInicial < 1 || mesInicial > 12) 
            throw new Exception ("Mês Inicial informado inválido");
        
        if (anoInicial < 1800 || anoInicial > year) 
            throw new Exception ("Ano Inicial informado inválido");
        
        if (diaFinal < 1 || diaFinal > 31) 
            throw new Exception ("Dia Final informado inválido");
        
        if (mesInicial < 1 || mesFinal > 12) 
            throw new Exception ("Mês Final informado inválido");
        
        if (anoFinal < 1800 || anoFinal > year) 
            throw new Exception ("Ano Final informado inválido");
        
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbGerarRelatorio;
    private javax.swing.JFormattedTextField jftDataFinal;
    private javax.swing.JFormattedTextField jftDataInicial;
    // End of variables declaration//GEN-END:variables
}
