/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sorveteria.view;

import Sorveteria.data.ClienteData;
import Sorveteria.data.ItensPedidoData;
import Sorveteria.data.PedidoData;
import Sorveteria.data.ProdutoData;
import Sorveteria.model.Cliente;
import Sorveteria.model.ItensPedido;
import Sorveteria.model.Pedido;
import Sorveteria.model.Produto;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kayo_
 */
public class JIFVenda extends javax.swing.JInternalFrame {
    Pedido objPedido;
    Cliente objCliente;
    Produto objProduto;
    ItensPedido objItensPedido;
    PedidoData DAOPedido;
    ClienteData DAOCliente;
    ProdutoData DAOProduto;
    ItensPedidoData DAOItensPedido;
    Float subTotal, valorTotal;
    Date dataHoraAtual;

    public JIFVenda() {
        
        
        try {
            objPedido = new Pedido();
            objCliente = new Cliente();
            objProduto = new Produto();
            objItensPedido = new ItensPedido();
            

            dataHoraAtual = new Date();
            
            DAOPedido = new PedidoData();
            DAOCliente = new ClienteData();
            DAOProduto = new ProdutoData();  
            DAOItensPedido = new ItensPedidoData();  
            
           
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,"Erro ao conectar: " + ex.getMessage());
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgCodigos = new javax.swing.ButtonGroup();
        jpDadosProduto = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jtIdProduto = new javax.swing.JTextField();
        jbPesquisarProduto = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jlTipo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jlSubTotal = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        spnQuantidade = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jlPreco = new javax.swing.JLabel();
        jbAdicionarItem = new javax.swing.JButton();
        jrbCodigoBanco = new javax.swing.JRadioButton();
        jrbCodigoBarras = new javax.swing.JRadioButton();
        jpDadosCliente = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtIdCliente = new javax.swing.JTextField();
        jbPesquisarCliente = new javax.swing.JButton();
        jlNomeCliente = new javax.swing.JLabel();
        jpDadosCarrinho = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbCarrinho = new javax.swing.JTable();
        jpDadosCliente1 = new javax.swing.JPanel();
        jlTotalVenda = new javax.swing.JLabel();
        jbFinalizar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("VENDA");

        jpDadosProduto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados do Produto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));
        jpDadosProduto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel3.setText("codigo:");

        jbPesquisarProduto.setText("Pesquisar");
        jbPesquisarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarProdutoActionPerformed(evt);
            }
        });

        jLabel4.setText("Produto:");

        jlTipo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlTipo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlTipo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jlTipo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel5.setText("Preço:");

        jlSubTotal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlSubTotal.setForeground(new java.awt.Color(255, 51, 51));
        jlSubTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlSubTotal.setText("R$ 0.00");
        jlSubTotal.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jlSubTotal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel6.setText("Quantidade:");

        spnQuantidade.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        spnQuantidade.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnQuantidadeStateChanged(evt);
            }
        });

        jLabel7.setText("SUBTOTAL:");

        jlPreco.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlPreco.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlPreco.setText("R$ 0.00");
        jlPreco.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jlPreco.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jbAdicionarItem.setText("ADICIONAR ITEM");
        jbAdicionarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAdicionarItemActionPerformed(evt);
            }
        });

        bgCodigos.add(jrbCodigoBanco);
        jrbCodigoBanco.setSelected(true);
        jrbCodigoBanco.setText("Código Interno");

        bgCodigos.add(jrbCodigoBarras);
        jrbCodigoBarras.setText("Código de Barras");

        javax.swing.GroupLayout jpDadosProdutoLayout = new javax.swing.GroupLayout(jpDadosProduto);
        jpDadosProduto.setLayout(jpDadosProdutoLayout);
        jpDadosProdutoLayout.setHorizontalGroup(
            jpDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDadosProdutoLayout.createSequentialGroup()
                .addGroup(jpDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDadosProdutoLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jpDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jpDadosProdutoLayout.createSequentialGroup()
                                .addGroup(jpDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jpDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpDadosProdutoLayout.createSequentialGroup()
                                        .addComponent(jtIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbPesquisarProduto)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jpDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jrbCodigoBanco)
                                            .addComponent(jrbCodigoBarras)))
                                    .addComponent(jlTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpDadosProdutoLayout.createSequentialGroup()
                                .addGroup(jpDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jbAdicionarItem, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jpDadosProdutoLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(jlPreco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(24, 24, 24)
                                        .addComponent(jLabel6)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spnQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jpDadosProdutoLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
        );
        jpDadosProdutoLayout.setVerticalGroup(
            jpDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDadosProdutoLayout.createSequentialGroup()
                .addGroup(jpDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDadosProdutoLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jpDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jbPesquisarProduto)))
                    .addGroup(jpDadosProdutoLayout.createSequentialGroup()
                        .addComponent(jrbCodigoBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrbCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1)
                .addGroup(jpDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDadosProdutoLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel4))
                    .addGroup(jpDadosProdutoLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jlTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addGroup(jpDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jlPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(spnQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addGap(41, 41, 41)
                .addGroup(jpDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jlSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jbAdicionarItem, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        jpDadosCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados do Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));
        jpDadosCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setText("id:");

        jbPesquisarCliente.setText("Pesquisar");
        jbPesquisarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarClienteActionPerformed(evt);
            }
        });

        jlNomeCliente.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jlNomeCliente.setText("Nome do Cliente");

        javax.swing.GroupLayout jpDadosClienteLayout = new javax.swing.GroupLayout(jpDadosCliente);
        jpDadosCliente.setLayout(jpDadosClienteLayout);
        jpDadosClienteLayout.setHorizontalGroup(
            jpDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDadosClienteLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbPesquisarCliente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpDadosClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlNomeCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpDadosClienteLayout.setVerticalGroup(
            jpDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDadosClienteLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jpDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbPesquisarCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlNomeCliente)
                .addContainerGap())
        );

        jpDadosCarrinho.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Carrinho de Compras", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));
        jpDadosCarrinho.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jtbCarrinho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Produto", "Valor Unitário", "Quantidade", "Subtotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbCarrinho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbCarrinhoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbCarrinho);

        javax.swing.GroupLayout jpDadosCarrinhoLayout = new javax.swing.GroupLayout(jpDadosCarrinho);
        jpDadosCarrinho.setLayout(jpDadosCarrinhoLayout);
        jpDadosCarrinhoLayout.setHorizontalGroup(
            jpDadosCarrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
        );
        jpDadosCarrinhoLayout.setVerticalGroup(
            jpDadosCarrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDadosCarrinhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jpDadosCliente1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Total da Venda", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 24))); // NOI18N
        jpDadosCliente1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jlTotalVenda.setBackground(new java.awt.Color(0, 0, 0));
        jlTotalVenda.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jlTotalVenda.setForeground(new java.awt.Color(102, 204, 0));
        jlTotalVenda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTotalVenda.setText("R$ 0.00");
        jlTotalVenda.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jlTotalVenda.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jpDadosCliente1Layout = new javax.swing.GroupLayout(jpDadosCliente1);
        jpDadosCliente1.setLayout(jpDadosCliente1Layout);
        jpDadosCliente1Layout.setHorizontalGroup(
            jpDadosCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpDadosCliente1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlTotalVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpDadosCliente1Layout.setVerticalGroup(
            jpDadosCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDadosCliente1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlTotalVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jbFinalizar.setText("FINALIZAR");
        jbFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFinalizarActionPerformed(evt);
            }
        });

        jbCancelar.setText("CANCELAR");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpDadosCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpDadosProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jpDadosCarrinho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpDadosCliente1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(91, 91, 91))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpDadosCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpDadosCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpDadosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jpDadosProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbPesquisarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisarClienteActionPerformed
        try {
            jlNomeCliente.setText(DAOCliente.retornarNome(Integer.parseInt(jtIdCliente.getText())));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "erro: "+e.getMessage());
        }
        
        
    }//GEN-LAST:event_jbPesquisarClienteActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        this.limparCampos();
        DefaultTableModel mp = (DefaultTableModel)jtbCarrinho.getModel();
        mp.setNumRows(0);
        this.atribuirValorTotal(mp);
        jtIdCliente.setText("");
        jlNomeCliente.setText("Nome do Cliente");
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbPesquisarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisarProdutoActionPerformed
        
        if (jrbCodigoBanco.isSelected()) {
            int idProduto = Integer.parseInt(jtIdProduto.getText());
            
            try {
                objProduto = DAOProduto.retornarProduto(idProduto);
                jlTipo.setText(objProduto.getTipo());
                jlPreco.setText(""+objProduto.getPreco());
                jlSubTotal.setText(""+objProduto.getPreco());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "erro: "+e.getMessage());
            }
        }else{
            long codigo_barra = Long.parseLong(jtIdProduto.getText());
            
            try {
                objProduto = DAOProduto.retornarProdutoCodigoBarra(codigo_barra);
                jlTipo.setText(objProduto.getTipo());
                jlPreco.setText(""+objProduto.getPreco());
                jlSubTotal.setText(""+objProduto.getPreco());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "erro: "+e.getMessage());
            }
        }
        
        
        
        
        
    }//GEN-LAST:event_jbPesquisarProdutoActionPerformed

    private void spnQuantidadeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnQuantidadeStateChanged
        
        this.atribuirSubTotal();
        jlSubTotal.setText(subTotal.toString());
    }//GEN-LAST:event_spnQuantidadeStateChanged

    private void jbAdicionarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAdicionarItemActionPerformed

        
        try {   
            
            this.atribuirSubTotal();
            if (jrbCodigoBanco.isSelected()) objProduto = DAOProduto.retornarProduto(Integer.parseInt(jtIdProduto.getText()));    
            else objProduto = DAOProduto.retornarProdutoCodigoBarra(Long.parseLong(jtIdProduto.getText()));
            DefaultTableModel mp = (DefaultTableModel)jtbCarrinho.getModel();
            
            /// "Código", "Produto", "Valor Unitário", "Quantidade", "Subtotal"

            mp.addRow(new String[]{""+objProduto.getIdProduto(),objProduto.getTipo(),""+objProduto.getPreco(),""+(Integer)spnQuantidade.getValue(),""+subTotal});
            
            this.atribuirValorTotal(mp);
            this.limparCampos();
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao pesquisar: "+e.getMessage());
        }
    }//GEN-LAST:event_jbAdicionarItemActionPerformed

    
    private void jtbCarrinhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbCarrinhoMouseClicked
        DefaultTableModel mp = (DefaultTableModel)jtbCarrinho.getModel();
        mp.removeRow(jtbCarrinho.getSelectedRow());
        this.atribuirValorTotal(mp);
    }//GEN-LAST:event_jtbCarrinhoMouseClicked

    private void jbFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFinalizarActionPerformed
        try{
            //validar dados
            if (validarDados()) {
                //preencher objeto
                if (preencherObjeto()) {
                        //incluir no banco
                        if(DAOPedido.incluir(objPedido)){
                            //mostrar menssagem 
                            JOptionPane.showMessageDialog(rootPane, "Salvo com sucesso", "Salvar", JOptionPane.WARNING_MESSAGE);
                            //limpar a tela
                            jbCancelarActionPerformed(evt);
                        }else{
                            JOptionPane.showMessageDialog(this, "Erro ao salvar: ", "Salvar-Produto", JOptionPane.ERROR_MESSAGE);
                        } 
                }
            }

        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "Erro ao salvar: " + e.getMessage(), "Salvar-Produto", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbFinalizarActionPerformed
    
    private void atribuirSubTotal(){
     subTotal = Float.parseFloat(jlPreco.getText()) * (Integer)spnQuantidade.getValue();
    }
    
    private void atribuirValorTotal(DefaultTableModel mp){
    valorTotal = (float)0;    
        
        for (int i = 0; i < mp.getRowCount(); i++) {
            valorTotal += Float.parseFloat(mp.getValueAt(i,4).toString());
        }
        
        
        //JOptionPane.showMessageDialog(this, ""+valorTotal);
        jlTotalVenda.setText(valorTotal.toString());
    }
    
    private void limparCampos(){
        
        spnQuantidade.setValue(1);
        jlPreco.setText("R$ 0.00");
        jlSubTotal.setText("R$ 0.00");
        jtIdProduto.setText("");
        jlTipo.setText("");
        
        
    }
    
    private boolean preencherObjeto() throws Exception{

       try {
           
               objPedido.setIdCliente(Integer.parseInt(jtIdCliente.getText()));
               objPedido.setTotal(Float.parseFloat(jlTotalVenda.getText()));
               
                for (int i = 0; i < jtbCarrinho.getRowCount(); i++) {
                    //JOptionPane.showMessageDialog(this, "0:"+jtbCarrinho.getValueAt(i, 0).toString());
                    //JOptionPane.showMessageDialog(this, "1:"+jtbCarrinho.getValueAt(i, 1).toString());
                    //JOptionPane.showMessageDialog(this, "2:"+jtbCarrinho.getValueAt(i, 2).toString());
                    //JOptionPane.showMessageDialog(this, "3:"+jtbCarrinho.getValueAt(i, 3).toString());
                    //JOptionPane.showMessageDialog(this, "4:"+jtbCarrinho.getValueAt(i, 4).toString());
                    objItensPedido = new ItensPedido();
                    objItensPedido.setIdProduto(Integer.parseInt(jtbCarrinho.getValueAt(i, 0).toString()));
                    objItensPedido.setValorUnitario(Float.parseFloat(jtbCarrinho.getValueAt(i, 2).toString()));
                    objItensPedido.setQuantidade(Integer.parseInt(jtbCarrinho.getValueAt(i, 3).toString()));
                    objItensPedido.setValor(Float.parseFloat(jtbCarrinho.getValueAt(i, 4).toString()));
                    objPedido.adicionarItem(objItensPedido);
                }
               
               
               
         
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao selecionar o registro: "+e.getMessage());
        }
        return true;
    }
    
    private boolean validarDados() throws Exception{
        if (jtIdCliente.getText().equals("")) 
            throw new Exception ("Insira o código do Cliente");
        
        if (jtbCarrinho.getRowCount() < 1) {
            throw new Exception ("Não há itens na compra!!");
        }
        return true;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgCodigos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAdicionarItem;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbFinalizar;
    private javax.swing.JButton jbPesquisarCliente;
    private javax.swing.JButton jbPesquisarProduto;
    private javax.swing.JLabel jlNomeCliente;
    private javax.swing.JLabel jlPreco;
    private javax.swing.JLabel jlSubTotal;
    private javax.swing.JLabel jlTipo;
    private javax.swing.JLabel jlTotalVenda;
    private javax.swing.JPanel jpDadosCarrinho;
    private javax.swing.JPanel jpDadosCliente;
    private javax.swing.JPanel jpDadosCliente1;
    private javax.swing.JPanel jpDadosProduto;
    private javax.swing.JRadioButton jrbCodigoBanco;
    private javax.swing.JRadioButton jrbCodigoBarras;
    private javax.swing.JTextField jtIdCliente;
    private javax.swing.JTextField jtIdProduto;
    private javax.swing.JTable jtbCarrinho;
    private javax.swing.JSpinner spnQuantidade;
    // End of variables declaration//GEN-END:variables
}

